//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsServices.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab_Tests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lab_Tests()
        {
            this.Lab_Mapping = new HashSet<Lab_Mapping>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public int Fee { get; set; }
        public bool Status { get; set; }
        public int Interval { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lab_Mapping> Lab_Mapping { get; set; }
    }
}
