//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsServices.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab_Parms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lab_Parms()
        {
            this.Lab_Mapping = new HashSet<Lab_Mapping>();
            this.PatientLabs_Labs_Parms = new HashSet<PatientLabs_Labs_Parms>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public string NormarVal { get; set; }
        public bool Status { get; set; }
        public Nullable<int> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lab_Mapping> Lab_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientLabs_Labs_Parms> PatientLabs_Labs_Parms { get; set; }
    }
}
