//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsServices.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientLab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientLab()
        {
            this.PatientLabs_Labs = new HashSet<PatientLabs_Labs>();
        }
    
        public long Id { get; set; }
        public string PatientNo { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public bool Gender { get; set; }
        public string RegisteredBy { get; set; }
        public string PerformedBy { get; set; }
        public System.DateTime Requested { get; set; }
        public Nullable<System.DateTime> Reported { get; set; }
        public string BloodGroup { get; set; }
        public string GuardianName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<bool> MaritalStatus { get; set; }
        public Nullable<int> Discount { get; set; }
        public string DiscountBy { get; set; }
        public Nullable<int> Amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientLabs_Labs> PatientLabs_Labs { get; set; }
    }
}
